import Head from 'next/head'

import Nav from '../components/Nav'
import Posts from '../components/Posts'

import {
  QUERY_GET_PRIMARY_MENU,
  QUERY_POSTS,
  QUERY_SETTINGS,
} from '../lib/queries'
import { request } from '../lib/request'

export default function Home({ settings, menu, posts }) {
  return (
    <div className='container-fluid'>
      <Head>
        <title>
          {settings.generalSettingsTitle} |{' '}
          {settings.generalSettingsDescription}
        </title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Nav menu={menu} brand={settings.generalSettingsTitle} />
      <Posts posts={posts} />
    </div>
  )
}

export async function getStaticProps() {
  const settings = await request(QUERY_SETTINGS)
  const menu = await request(QUERY_GET_PRIMARY_MENU)
  const posts = await request(QUERY_POSTS)
  return {
    props: {
      settings: settings.allSettings,
      menu: menu.menuItems.edges,
      posts: posts.posts.nodes,
    },
  }
}
